In [7]:
using Singular
#using Revise
import Nemo

In [8]:
CC = Nemo.ComplexField(64)

Complex Field with 64 bits of precision and error bounds

In [15]:
i = onei(CC)
s*i

0 + i*1.0000000000000000000

In [33]:
 P, (s,) = PolynomialRing(CC, ["s"])

v1 = vector(P, s + 1, s*s + 1, s)
v2 = vector(P, s^2 + 1, 2s + 3s, s)

M = Singular.Module(P, v1, v2)
G = std(M; complete_reduction=true)

mysyz = syz(M)

Singular Module over Singular Polynomial Ring (Coeffs(19)),(s),(dp(1),C), with Generators:
0

In [37]:
Singular.MatrixSpace(P,3,3)

MethodError: MethodError: no method matching Singular.MatrixSpace(::Singular.PolyRing{Singular.n_unknown{acb}}, ::Int64, ::Int64)

In [29]:
vector(P, [s, s, 1 + s]...)

s*gen(3)+s*gen(2)+s*gen(1)+gen(3)

In [38]:
v1 = vector(P, 1, 0, 0, 0)
i1 = vector(P, 0, 1, 0 ,0)
v2 = vector(P, 0, 0, 1, 0)
i2 = vector(P, 0, 0, 0 ,1)




MethodError: MethodError: no method matching vector(::Singular.PolyRing{Singular.n_unknown{acb}}, ::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  vector(::Singular.PolyRing{T}, !Matched::spoly{T}...) where T<:RingElem at /home/philip/.julia/packages/Singular/GGfzi/src/module/vector.jl:229

In [47]:
M = Singular.FreeModule(P, 4)
v1 = M([P(1), P(0), P(0),P(0)])
i1 = M([P(0), P(1), P(0),P(0)])
v2 = M([P(0), P(0), P(1),P(0)])
i2 = M([P(0), P(0), P(0),P(1)])

e1 = (v1 - v2) + 10 * i1 # current through resistor
e2 = 10i * s * v2 +  (i1 - i2)  # current conservation + capacitor.


(0 + i*10.000000000000000000)*s*gen(3)+(-1.0000000000000000000 + i*0)*gen(4)+gen(2)

In [53]:
v1,i1,v2,i2 = gens(M)
e1 = (v1 - v2) + 10 * i1 # current through resistor
e2 = 10i * s * v2 +  (i1 - i2)  # current conservation + capacitor.
G = Singular.Module(P,e1,e2)
syz(G) # no I need teh syzygies of the transpose of this matrix.

(0 + i*10.000000000000000000)*s*gen(3)+(-1.0000000000000000000 + i*0)*gen(4)+gen(2)

In [88]:
transpose(hcat([Array(G[i]) for i in 1:Singular.ngens(G)]...))

2×4 LinearAlgebra.Transpose{spoly{Singular.n_unknown{acb}},Array{spoly{Singular.n_unknown{acb}},2}}:
 (1.0000000000000000000 + i*0)  …  0
 0                                 (-1.0000000000000000000 + i*0)

In [107]:
G2 = Singular.Matrix(G)
M2 = Singular.Module(P, [  vector(P, [ G2[i,j] for j in 1:Singular.ncols(G2) ]...)  for i in 1:Singular.nrows(G2) ]...)
Singular.Matrix(syz(M2)) # I think these are the V-Rep of the currents and voltages

[(-10.000000000000000000 + i*0), (-10.000000000000000000 + i*0)*s+(0 + i*[0.100000000000000000 +/- 1.22e-20])
(1.0000000000000000000 + i*0), s
0, (0 + i*[0.100000000000000000 +/- 1.22e-20])
(1.0000000000000000000 + i*0), 0]

In [96]:
Singular.ncols())

4

In [87]:
?transpose

search: transpose transpose! n_transExt_to_spoly



```
transpose(A)
```

Lazy transpose. Mutating the returned object should appropriately mutate `A`. Often, but not always, yields `Transpose(A)`, where `Transpose` is a lazy transpose wrapper. Note that this operation is recursive.

This operation is intended for linear algebra usage - for general data manipulation see [`permutedims`](@ref Base.permutedims), which is non-recursive.

# Examples

```jldoctest
julia> A = [3+2im 9+2im; 8+7im  4+6im]
2×2 Array{Complex{Int64},2}:
 3+2im  9+2im
 8+7im  4+6im

julia> transpose(A)
2×2 Transpose{Complex{Int64},Array{Complex{Int64},2}}:
 3+2im  8+7im
 9+2im  4+6im
```

---

```
transpose(x::Mat)
```

> Return the transpose of the given matrix.


---

```
transpose(x::MatAlgElem{T}) where T <: RingElement
```

> Return the transpose of the given matrix.


---

transpose(M::smatrix{T}) where T <: AbstractAlgebra.RingElem

> Given a matrix $M=(m_{ij})_{i, j}$, return the matrix $M^T=(m_{ji})_{j, i}$.



In [79]:
rank(G)

4

In [46]:
P(s) # so i should just map P over everything to be safe

s

In [66]:
?Matrix

search: Matrix matrix MatrixElem MatrixSpace matrix_repr MatrixAlgebra smatrix



```
Matrix{T} <: AbstractMatrix{T}
```

Two-dimensional dense array with elements of type `T`, often used to represent a mathematical matrix. Alias for [`Array{T,2}`](@ref).

---

```
Matrix{T}(undef, m, n)
```

Construct an uninitialized [`Matrix{T}`](@ref) of size `m`×`n`. See [`undef`](@ref).

# Examples

```julia-repl
julia> Matrix{Float64}(undef, 2, 3)
2×3 Array{Float64,2}:
 6.93517e-310  6.93517e-310  6.93517e-310
 6.93517e-310  6.93517e-310  1.29396e-320
```

---

```
Matrix{T}(nothing, m, n)
```

Construct a [`Matrix{T}`](@ref) of size `m`×`n`, initialized with [`nothing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

# Examples

```jldoctest
julia> Matrix{Union{Nothing, String}}(nothing, 2, 3)
2×3 Array{Union{Nothing, String},2}:
 nothing  nothing  nothing
 nothing  nothing  nothing
```

---

```
Matrix{T}(missing, m, n)
```

Construct a [`Matrix{T}`](@ref) of size `m`×`n`, initialized with [`missing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

# Examples

```jldoctest
julia> Matrix{Union{Missing, String}}(missing, 2, 3)
2×3 Array{Union{Missing, String},2}:
 missing  missing  missing
 missing  missing  missing
```

---

```
Matrix(A::MatrixElem)
```

> Convert `A` to a Julia `Matrix` of the same dimensions with the same elements.


# Examples

```jldoctest; setup = :(using AbstractAlgebra)
julia> A = ZZ[1 2 3; 4 5 6]
[1  2  3]
[4  5  6]

julia> Matrix(A)
2×3 Array{BigInt,2}:
 1  2  3
 4  5  6
```


In [31]:
M
M = FreeModule(R, 3)
v2 = M([x + 1, x*y + 1, y])
V = Array(v1)

Singular Module over Singular Polynomial Ring (Coeffs(19)),(s),(dp(1),C), with Generators:
s^2*gen(2)+s*gen(3)+s*gen(1)+gen(2)+gen(1)
s^2*gen(1)+s*gen(3)+(5.0000000000000000000 + i*0)*s*gen(2)+gen(1)

In [23]:
M[2] # ok I have access to the inidivudal boys

s^2*gen(1)+s*gen(3)+(5.0000000000000000000 + i*0)*s*gen(2)+gen(1)

In [19]:
R, (s,) = PolynomialRing(QQ, ["s"])

v1 = vector(R, s + 1, s*s + 1, s)
v2 = vector(R, s^2 + 1, 2s + 3s, s)

M = Singular.Module(R, v1, v2)

G = std(M; complete_reduction=true)

mysyz = syz(M)

Singular Module over Singular Polynomial Ring (QQ),(s),(dp(1),C), with Generators:
0

In [5]:
struct BIzboy
   ins
   outs
end







i0 * R = v2 - v1

jC  

ok here's an immediate glitch. I don't see ocmplex numbers in singular

maybe I can access it via nemo, but nemo already has smith normnal form?

v1    v2     v3

In [6]:
module Experiment
    struct Foo
            bar :: Int
    end
end

Main.Experiment

In [8]:
Experiment.Foo(3)

Main.Experiment.Foo(3)

In [7]:
R, (x, y) = PolynomialRing(QQ, ["x", "y"])

(Singular Polynomial Ring (QQ),(x,y),(dp(2),C), spoly{n_Q}[x, y])

In [11]:
x^2 + 1

x^2+1

In [14]:
I = Ideal(R, x^2 +1, x*y + 1)

Singular Ideal over Singular Polynomial Ring (QQ),(x,y),(dp(2),C) with generators (x^2+1, x*y+1)

In [22]:
G = std(I)
Z = syz(G)
F = fres(G,0)
F[1]
F[2]


Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
-y^2*gen(1)+x*gen(2)-y*gen(2)-gen(1)

In [23]:
S = @PolynomialRing(ZZ, "x", 5, :deglex) # make a 5 variable polynomial

Singular Polynomial Ring (ZZ),(x1,x2,x3,x4,x5),(Dp(5),C)

In [37]:
R, (x, y) = PolynomialRing(QQ, ["x", "y"])

I = Ideal(R, x^2*y + 2y + 1, y^2 + 1)

F = syz(I)

M = Singular.Matrix(I)
N = Singular.Matrix(F)
println(F)
println(M * N)
println(N)

Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
x^2*y*gen(2)-y^2*gen(1)+2*y*gen(2)+gen(2)-gen(1)
[0]
[-y^2-1
x^2*y+2*y+1]


In [4]:
R, (s,) = PolynomialRing(QQ, ["s"])

(Singular Polynomial Ring (QQ),(s),(dp(1),C), spoly{n_Q}[s])

In [6]:
x + 1

MethodError: MethodError: no method matching +(::Array{spoly{n_Q},1}, ::Int64)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  +(!Matched::Complex{Bool}, ::Real) at complex.jl:297
  +(!Matched::Missing, ::Number) at missing.jl:115
  ...

In [9]:
R, (x, y) = PolynomialRing(QQ, ["x", "y"])

v1 = vector(R, x + 1, x*y + 1, y)
v2 = vector(R, x^2 + 1, 2x + 3y, x)

M = Singular.Module(R, v1, v2)
rank(M)

3

In [10]:
M

Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
x*y*gen(2)+x*gen(1)+y*gen(3)+gen(2)+gen(1)
x^2*gen(1)+x*gen(3)+2*x*gen(2)+3*y*gen(2)+gen(1)

In [12]:
fieldnames(M)

MethodError: MethodError: no method matching fieldnames(::smodule{spoly{n_Q}})
Closest candidates are:
  fieldnames(!Matched::Core.TypeofBottom) at reflection.jl:175
  fieldnames(!Matched::Type{#s8} where #s8<:Tuple) at reflection.jl:177
  fieldnames(!Matched::DataType) at reflection.jl:172
  ...